FROM java:8
ADD projekt-scs/build/libs/projekt-scs-0.0.1-SNAPSHOT.jar projekt-scs.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "projekt-scs.jar"]
ENV DOCKERIZE_VERSION v0.6.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

CMD dockerize -wait tcp://db:3306 -timeout 60m yarn start
